language: php

dist: trusty
sudo: false

matrix:
  fast_finish: true
  include:
    - php: '7.3'
      env: SYMFONY_VERSION='5.3.*'

before_install:
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony=$SYMFONY_VERSION; fi

install:
  - composer update $COMPOSER_FLAGS --prefer-dist --prefer-stable

script:
  - vendor/bin/simple-phpunit
